### ISSUE TITLE
Add support for custom file format for results

### ISSUE THREAD

**Issue by rohitxsh** [rohitxsh/ensembl_lakehouse#10]
Athena stores the results in CSV format, implement a microservice to convert the CSV format to different file formats for ex. JSON, TSV, XML etc.

**Comment by rohitxsh** [comment]
@andrewyatz @marcoooo @bilalebi Can you please share a list of result file formats we will supporting as of now

**Comment by marcoooo** [comment]
@rohitxsh I believe we are good with the ones mentioned, e.g. JSON - TSV - XML
